# Generated by Django 5.1.7 on 2025-03-11 13:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Untitled Assignment', max_length=255)),
                ('degree', models.CharField(blank=True, max_length=255, null=True)),
                ('module', models.CharField(blank=True, max_length=255, null=True)),
                ('instructions', models.TextField(blank=True, null=True)),
                ('deadline', models.DateField(blank=True, null=True)),
                ('brief', models.FileField(blank=True, null=True, upload_to='assignments/')),
                ('payment_status', models.CharField(default='unpaid', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='NonPremiumAssignment',
            fields=[
            ],
            options={
                'verbose_name': 'Non-Premium Assignment',
                'verbose_name_plural': 'Non-Premium Assignments',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('assignments.assignment',),
        ),
        migrations.CreateModel(
            name='PremiumAssignment',
            fields=[
            ],
            options={
                'verbose_name': 'Premium Assignment',
                'verbose_name_plural': 'Premium Assignments',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('assignments.assignment',),
        ),
    ]
