# Generated by Django 5.1.7 on 2025-03-11 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0002_assignment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='completed_file',
            field=models.FileField(blank=True, null=True, upload_to='completed_assignments/'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in-progress', 'In Progress'), ('completed', 'Completed')], default='pending', max_length=20),
        ),
    ]
