# Generated by Django 5.1.7 on 2025-03-11 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0003_assignment_completed_file_alter_assignment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='completed_file',
            field=models.FileField(blank=True, null=True, upload_to='assignments/completed/'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='status',
            field=models.CharField(choices=[('processing', 'Processing'), ('completed', 'Completed')], default='processing', max_length=20),
        ),
    ]
