# Generated by Django 5.1.7 on 2025-03-13 11:55

import storages.backends.s3
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0004_alter_assignment_completed_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='brief',
            field=models.FileField(blank=True, null=True, storage=storages.backends.s3.S3Storage(), upload_to='assignments/'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='completed_file',
            field=models.FileField(blank=True, null=True, storage=storages.backends.s3.S3Storage(), upload_to='assignments/completed/'),
        ),
    ]
