# Generated by Django 5.1.7 on 2025-03-13 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0005_alter_assignment_brief_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='payment_status',
            field=models.CharField(choices=[('unpaid', 'Unpaid'), ('pending', 'Pending'), ('paid', 'Paid')], default='unpaid', max_length=50),
        ),
    ]
