# Generated by Django 5.1.7 on 2025-03-14 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0006_alter_assignment_payment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='brief',
            field=models.FileField(blank=True, null=True, upload_to='assignments/'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='completed_file',
            field=models.FileField(blank=True, null=True, upload_to='assignments/completed/'),
        ),
    ]
